---
version: "3.9"

services:
  cloudbeaver:
    build: ./services/cloudbeaver
    depends_on:
      - payroll_db
    ports:
      - "8080:8978"
  payroll_db:
    build: ./services/db/payroll
    ports:
      - "5432:5432"
